
Adana:
1		ALADAĞ		ADANA		
2		CEYHAN		ADANA		
3		ÇUKUROVA		ADANA		
4		FEKE		ADANA		
5		İMAMOĞLU		ADANA		
6		KARAİSALI		ADANA		
7		KARATAŞ		ADANA		
8		KOZAN		ADANA		
9		POZANTI		ADANA		
10		SAİMBEYLİ		ADANA		
11		SARIÇAM		ADANA		
12		SEYHAN		ADANA		
13		TUFANBEYLİ		ADANA		
14		YUMURTALIK		ADANA		
15		YÜREĞİR		ADANA		

Adıyaman:
1		BESNİ		ADIYAMAN		
2		ÇELİKHAN		ADIYAMAN		
3		GERGER		ADIYAMAN		
4		GÖLBAŞI		ADIYAMAN		
5		KAHTA		ADIYAMAN		
6		SAMSAT		ADIYAMAN		
7		SİNCİK		ADIYAMAN		
8		TUT		ADIYAMAN		

Afyonkarahisar:
1		BAŞMAKÇI		AFYONKARAHİSAR		
2		BAYAT		AFYONKARAHİSAR		
3		BOLVADİN		AFYONKARAHİSAR		
4		ÇAY		AFYONKARAHİSAR		
5		ÇOBANLAR		AFYONKARAHİSAR		
6		DAZKIRI		AFYONKARAHİSAR		
7		DİNAR		AFYONKARAHİSAR		
8		EMİRDAĞ		AFYONKARAHİSAR		
9		EVCİLER		AFYONKARAHİSAR		
10		HOCALAR		AFYONKARAHİSAR		
11		İHSANİYE		AFYONKARAHİSAR		
12		İSCEHİSAR		AFYONKARAHİSAR		
13		KIZILÖREN		AFYONKARAHİSAR		
14		SANDIKLI		AFYONKARAHİSAR		
15		SİNANPAŞA		AFYONKARAHİSAR		
16		SULTANDAĞI		AFYONKARAHİSAR		
17		ŞUHUT		AFYONKARAHİSAR		

Ağrı:
1		DİYADİN		AĞRI		
2		DOĞUBAYAZIT		AĞRI		
3		ELEŞKİRT		AĞRI		
4		HAMUR		AĞRI		
5		PATNOS		AĞRI		
6		TAŞLIÇAY		AĞRI		
7		TUTAK		AĞRI		

Aksaray:
1		AĞAÇÖREN		AKSARAY		
2		ESKİL		AKSARAY		
3		GÜLAĞAÇ		AKSARAY		
4		GÜZELYURT		AKSARAY		
5		ORTAKÖY		AKSARAY		
6		SARIYAHŞİ		AKSARAY		
7		SULTANHANI		AKSARAY		

Amasyа:
1		GÖYNÜCEK		AMASYA		
2		GÜMÜŞHACIKÖY		AMASYA		
3		HAMAMÖZÜ		AMASYA		
4		MERZİFON		AMASYA		
5		SULUOVA		AMASYA		
6		TAŞOVA		AMASYA		

Ankara:
1		AKYURT		ANKARA		
2		ALTINDAĞ		ANKARA		
3		AYAŞ		ANKARA		
4		BALA		ANKARA		
5		BEYPAZARI		ANKARA		
6		ÇAMLIDERE		ANKARA		
7		ÇANKAYA		ANKARA		
8		ÇUBUK		ANKARA		
9		ELMADAĞ		ANKARA		
10		ETİMESGUT		ANKARA		
11		EVREN		ANKARA		
12		GÖLBAŞI		ANKARA		
13		GÜDÜL		ANKARA		
14		HAYMANA		ANKARA		
15		KAHRAMANKAZAN		ANKARA		
16		KALECİK		ANKARA		
17		KEÇİÖREN		ANKARA		
18		KIZILCAHAMAM		ANKARA		
19		MAMAK		ANKARA		
20		NALLIHAN		ANKARA		
21		POLATLI		ANKARA		
22		PURSAKLAR		ANKARA		
23		SİNCAN		ANKARA		
24		ŞEREFLİKOÇHİSAR		ANKARA		
25		YENİMAHALLE		ANKARA		

Antalya:
1		AKSEKİ		ANTALYA		
2		AKSU		ANTALYA		
3		ALANYA		ANTALYA		
4		DEMRE		ANTALYA		
5		DÖŞEMEALTI		ANTALYA		
6		ELMALI		ANTALYA		
7		FİNİKE		ANTALYA		
8		GAZİPAŞA		ANTALYA		
9		GÜNDOĞMUŞ		ANTALYA		
10		İBRADI		ANTALYA		
11		KAŞ		ANTALYA		
12		KEMER		ANTALYA		
13		KEPEZ		ANTALYA		
14		KONYAALTI		ANTALYA		
15		KORKUTELİ		ANTALYA		
16		KUMLUCA		ANTALYA		
17		MANAVGAT		ANTALYA		
18		MURATPAŞA		ANTALYA		
19		SERİK		ANTALYA		

Ardahan:
1		ÇILDIR		ARDAHAN		
2		DAMAL		ARDAHAN		
3		GÖLE		ARDAHAN		
4		HANAK		ARDAHAN		
5		POSOF		ARDAHAN		


Artvin:
1		ARDANUÇ		ARTVİN		
2		ARHAVİ		ARTVİN		
3		BORÇKA		ARTVİN		
4		HOPA		ARTVİN		
5		KEMALPAŞA		ARTVİN		
6		MURGUL		ARTVİN		
7		ŞAVŞAT		ARTVİN		
8		YUSUFELİ		ARTVİN		

Aydın:
1		BOZDOĞAN		AYDIN		
2		BUHARKENT		AYDIN		
3		ÇİNE		AYDIN		
4		DİDİM		AYDIN		
5		EFELER		AYDIN		
6		GERMENCİK		AYDIN		
7		İNCİRLİOVA		AYDIN		
8		KARACASU		AYDIN		
9		KARPUZLU		AYDIN		
10		KOÇARLI		AYDIN		
11		KÖŞK		AYDIN		
12		KUŞADASI		AYDIN		
13		KUYUCAK		AYDIN		
14		NAZİLLİ		AYDIN		
15		SÖKE		AYDIN		
16		SULTANHİSAR		AYDIN		
17		YENİPAZAR		AYDIN		

Balıkesir:
1		ALTIEYLÜL		BALIKESİR		
2		AYVALIK		BALIKESİR		
3		BALYA		BALIKESİR		
4		BANDIRMA		BALIKESİR		
5		BİGADİÇ		BALIKESİR		
6		BURHANİYE		BALIKESİR		
7		DURSUNBEY		BALIKESİR		
8		EDREMİT		BALIKESİR		
9		ERDEK		BALIKESİR		
10		GÖMEÇ		BALIKESİR		
11		GÖNEN		BALIKESİR		
12		HAVRAN		BALIKESİR		
13		İVRİNDİ		BALIKESİR		
14		KARESİ		BALIKESİR		
15		KEPSUT		BALIKESİR		
16		MANYAS		BALIKESİR		
17		MARMARA		BALIKESİR		
18		SAVAŞTEPE		BALIKESİR		
19		SINDIRGI		BALIKESİR		
20		SUSURLUK		BALIKESİR		

Bartın:
1		AMASRA		BARTIN		
2		KURUCAŞİLE		BARTIN		
3		ULUS		BARTIN		

Batman:
1		BEŞİRİ		BATMAN		
2		GERCÜŞ		BATMAN		
3		HASANKEYF		BATMAN		
4		KOZLUK		BATMAN		
5		SASON		BATMAN		

Bayburt:
1		AYDINTEPE		BAYBURT		
2		DEMİRÖZÜ		BAYBURT		

Bilecik:
1		BOZÜYÜK		BİLECİK		
2		GÖLPAZARI		BİLECİK		
3		İNHİSAR		BİLECİK		
4		OSMANELİ		BİLECİK		
5		PAZARYERİ		BİLECİK		
6		SÖĞÜT		BİLECİK		
7		YENİPAZAR		BİLECİK		

Bingöl:
1		ADAKLI		BİNGÖL		
2		GENÇ		BİNGÖL		
3		KARLIOVA		BİNGÖL		
4		KİĞI		BİNGÖL		
5		SOLHAN		BİNGÖL		
6		YAYLADERE		BİNGÖL		
7		YEDİSU		BİNGÖL		

Bitlis:
1		ADİLCEVAZ		BİTLİS		
2		AHLAT		BİTLİS		
3		GÜROYMAK		BİTLİS		
4		HİZAN		BİTLİS		
5		MUTKİ		BİTLİS		
6		TATVAN		BİTLİS		

Bolu:
1		DÖRTDİVAN		BOLU		
2		GEREDE		BOLU		
3		GÖYNÜK		BOLU		
4		KIBRISCIK		BOLU		
5		MENGEN		BOLU		
6		MUDURNU		BOLU		
7		SEBEN		BOLU		
8		YENİÇAĞA		BOLU		

Burdur:
1		AĞLASUN		BURDUR		
2		ALTINYAYLA		BURDUR		
3		BUCAK		BURDUR		
4		ÇAVDIR		BURDUR		
5		ÇELTİKÇİ		BURDUR		
6		GÖLHİSAR		BURDUR		
7		KARAMANLI		BURDUR		
8		KEMER		BURDUR		
9		TEFENNİ		BURDUR		
10		YEŞİLOVA		BURDUR		

Bursa:
1		BÜYÜKORHAN		BURSA		
2		GEMLİK		BURSA		
3		GÜRSU		BURSA		
4		HARMANCIK		BURSA		
5		İNEGÖL		BURSA		
6		İZNİK		BURSA		
7		KARACABEY		BURSA		
8		KELES		BURSA		
9		KESTEL		BURSA		
10		MUDANYA		BURSA		
11		MUSTAFAKEMALPAŞA		BURSA		
12		NİLÜFER		BURSA		
13		ORHANELİ		BURSA		
14		ORHANGAZİ		BURSA		
15		OSMANGAZİ		BURSA		
16		YENİŞEHİR		BURSA		
17		YILDIRIM		BURSA		

Çanakkale:
1		AYVACIK		ÇANAKKALE		
2		BAYRAMİÇ		ÇANAKKALE		
3		BİGA		ÇANAKKALE		
4		BOZCAADA		ÇANAKKALE		
5		ÇAN		ÇANAKKALE		
6		ECEABAT		ÇANAKKALE		
7		EZİNE		ÇANAKKALE		
8		GELİBOLU		ÇANAKKALE		
9		GÖKÇEADA		ÇANAKKALE		
10		LAPSEKİ		ÇANAKKALE		
11		YENİCE		ÇANAKKALE		

Çankırı:
1		ATKARACALAR		ÇANKIRI		
2		BAYRAMÖREN		ÇANKIRI		
3		ÇERKEŞ		ÇANKIRI		
4		ELDİVAN		ÇANKIRI		
5		ILGAZ		ÇANKIRI		
6		KIZILIRMAK		ÇANKIRI		
7		KORGUN		ÇANKIRI		
8		KURŞUNLU		ÇANKIRI		
9		ORTA		ÇANKIRI		
10		ŞABANÖZÜ		ÇANKIRI		
11		YAPRAKLI		ÇANKIRI		

Çorum:
						
1		ALACA		ÇORUM		
2		BAYAT		ÇORUM		
3		BOĞAZKALE		ÇORUM		
4		DODURGA		ÇORUM		
5		İSKİLİP		ÇORUM		
6		KARGI		ÇORUM		
7		LAÇİN		ÇORUM		
8		MECİTÖZÜ		ÇORUM		
9		OĞUZLAR		ÇORUM		
10		ORTAKÖY		ÇORUM		
11		OSMANCIK		ÇORUM		
12		SUNGURLU		ÇORUM		
13		UĞURLUDAĞ		ÇORUM		

Denizli:
1		ACIPAYAM		DENİZLİ		
2		BABADAĞ		DENİZLİ		
3		BAKLAN		DENİZLİ		
4		BEKİLLİ		DENİZLİ		
5		BEYAĞAÇ		DENİZLİ		
6		BOZKURT		DENİZLİ		
7		BULDAN		DENİZLİ		
8		ÇAL		DENİZLİ		
9		ÇAMELİ		DENİZLİ		
10		ÇARDAK		DENİZLİ		
11		ÇİVRİL		DENİZLİ		
12		GÜNEY		DENİZLİ		
13		HONAZ		DENİZLİ		
14		KALE		DENİZLİ		
15		MERKEZEFENDİ		DENİZLİ		
16		PAMUKKALE		DENİZLİ		
17		SARAYKÖY		DENİZLİ		
18		SERİNHİSAR		DENİZLİ		
19		TAVAS		DENİZLİ		

Diyarbakır:
1		BAĞLAR		DİYARBAKIR		
2		BİSMİL		DİYARBAKIR		
3		ÇERMİK		DİYARBAKIR		
4		ÇINAR		DİYARBAKIR		
5		ÇÜNGÜŞ		DİYARBAKIR		
6		DİCLE		DİYARBAKIR		
7		EĞİL		DİYARBAKIR		
8		ERGANİ		DİYARBAKIR		
9		HANİ		DİYARBAKIR		
10		HAZRO		DİYARBAKIR		
11		KAYAPINAR		DİYARBAKIR		
12		KOCAKÖY		DİYARBAKIR		
13		KULP		DİYARBAKIR		
14		LİCE		DİYARBAKIR		
15		SİLVAN		DİYARBAKIR		
16		SUR		DİYARBAKIR		
17		YENİŞEHİR		DİYARBAKIR		

Düzce:
1		AKÇAKOCA		DÜZCE		
2		CUMAYERİ		DÜZCE		
3		ÇİLİMLİ		DÜZCE		
4		GÖLYAKA		DÜZCE		
5		GÜMÜŞOVA		DÜZCE		
6		KAYNAŞLI		DÜZCE		
7		YIĞILCA		DÜZCE		

Edirne:
1		ENEZ		EDİRNE		
2		HAVSA		EDİRNE		
3		İPSALA		EDİRNE		
4		KEŞAN		EDİRNE		
5		LALAPAŞA		EDİRNE		
6		MERİÇ		EDİRNE		
7		SÜLOĞLU		EDİRNE		
8		UZUNKÖPRÜ		EDİRNE		

Elazığ:
1		AĞIN		ELAZIĞ		
2		ALACAKAYA		ELAZIĞ		
3		ARICAK		ELAZIĞ		
4		BASKİL		ELAZIĞ		
5		KARAKOÇAN		ELAZIĞ		
6		KEBAN		ELAZIĞ		
7		KOVANCILAR		ELAZIĞ		
8		MADEN		ELAZIĞ		
9		PALU		ELAZIĞ		
10		SİVRİCE		ELAZIĞ		

Erzincan:
1		ÇAYIRLI		ERZİNCAN		
2		İLİÇ		ERZİNCAN		
3		KEMAH		ERZİNCAN		
4		KEMALİYE		ERZİNCAN		
5		OTLUKBELİ		ERZİNCAN		
6		REFAHİYE		ERZİNCAN		
7		TERCAN		ERZİNCAN		
8		ÜZÜMLÜ		ERZİNCAN		

Erzurum:
1		AŞKALE		ERZURUM		
2		AZİZİYE		ERZURUM		
3		ÇAT		ERZURUM		
4		HINIS		ERZURUM		
5		HORASAN		ERZURUM		
6		İSPİR		ERZURUM		
7		KARAÇOBAN		ERZURUM		
8		KARAYAZI		ERZURUM		
9		KÖPRÜKÖY		ERZURUM		
10		NARMAN		ERZURUM		
11		OLTU		ERZURUM		
12		OLUR		ERZURUM		
13		PALANDÖKEN		ERZURUM		
14		PASİNLER		ERZURUM		
15		PAZARYOLU		ERZURUM		
16		ŞENKAYA		ERZURUM		
17		TEKMAN		ERZURUM		
18		TORTUM		ERZURUM		
19		UZUNDERE		ERZURUM		
20		YAKUTİYE		ERZURUM		

Eskişehir:
1		ALPU		ESKİŞEHİR		
2		BEYLİKOVA		ESKİŞEHİR		
3		ÇİFTELER		ESKİŞEHİR		
4		GÜNYÜZÜ		ESKİŞEHİR		
5		HAN		ESKİŞEHİR		
6		İNÖNÜ		ESKİŞEHİR		
7		MAHMUDİYE		ESKİŞEHİR		
8		MİHALGAZİ		ESKİŞEHİR		
9		MİHALIÇÇIK		ESKİŞEHİR		
10		ODUNPAZARI		ESKİŞEHİR		
11		SARICAKAYA		ESKİŞEHİR		
12		SEYİTGAZİ		ESKİŞEHİR		
13		SİVRİHİSAR		ESKİŞEHİR		
14		TEPEBAŞI		ESKİŞEHİR		

Gaziantep:
1		ARABAN		GAZİANTEP		
2		İSLAHİYE		GAZİANTEP		
3		KARKAMIŞ		GAZİANTEP		
4		NİZİP		GAZİANTEP		
5		NURDAĞI		GAZİANTEP		
6		OĞUZELİ		GAZİANTEP		
7		ŞAHİNBEY		GAZİANTEP		
8		ŞEHİTKAMİL		GAZİANTEP		
9		YAVUZELİ		GAZİANTEP		

Giresun:
1		ALUCRA		GİRESUN		
2		BULANCAK		GİRESUN		
3		ÇAMOLUK		GİRESUN		
4		ÇANAKÇI		GİRESUN		
5		DERELİ		GİRESUN		
6		DOĞANKENT		GİRESUN		
7		ESPİYE		GİRESUN		
8		EYNESİL		GİRESUN		
9		GÖRELE		GİRESUN		
10		GÜCE		GİRESUN		
11		KEŞAP		GİRESUN		
12		PİRAZİZ		GİRESUN		
13		ŞEBİNKARAHİSAR		GİRESUN		
14		TİREBOLU		GİRESUN		
15		YAĞLIDERE		GİRESUN		

Gümüşhane:
1		KELKİT		GÜMÜŞHANE		
2		KÖSE		GÜMÜŞHANE		
3		KÜRTÜN		GÜMÜŞHANE		
4		ŞİRAN		GÜMÜŞHANE		
5		TORUL		GÜMÜŞHANE		

Hakkari:
1		ÇUKURCA		HAKKARİ		
2		DERECİK		HAKKARİ		
3		ŞEMDİNLİ		HAKKARİ		
4		YÜKSEKOVA		HAKKARİ		

Hatay:
1		ALTINÖZÜ		HATAY		
2		ANTAKYA		HATAY		
3		ARSUZ		HATAY		
4		BELEN		HATAY		
5		DEFNE		HATAY		
6		DÖRTYOL		HATAY		
7		ERZİN		HATAY		
8		HASSA		HATAY		
9		İSKENDERUN		HATAY		
10		KIRIKHAN		HATAY		
11		KUMLU		HATAY		
12		PAYAS		HATAY		
13		REYHANLI		HATAY		
14		SAMANDAĞ		HATAY		
15		YAYLADAĞI		HATAY		

Iğdır:
1		ARALIK		IĞDIR		
2		KARAKOYUNLU		IĞDIR		
3		TUZLUCA		IĞDIR		

Isparta:
1		AKSU		ISPARTA		
2		ATABEY		ISPARTA		
3		EĞİRDİR		ISPARTA		
4		GELENDOST		ISPARTA		
5		GÖNEN		ISPARTA		
6		KEÇİBORLU		ISPARTA		
7		SENİRKENT		ISPARTA		
8		SÜTÇÜLER		ISPARTA		
9		ŞARKİKARAAĞAÇ		ISPARTA		
10		ULUBORLU		ISPARTA		
11		YALVAÇ		ISPARTA		
12		YENİŞARBADEMLİ		ISPARTA		

Istanbul:
1		ADALAR		ISTANBUL		
2		ARNAVUTKÖY		ISTANBUL		
3		ATAŞEHİR		ISTANBUL		
4		AVCILAR		ISTANBUL		
5		BAĞCILAR		ISTANBUL		
6		BAHÇELİEVLER		ISTANBUL		
7		BAKIRKÖY		ISTANBUL		
8		BAŞAKŞEHİR		ISTANBUL		
9		BAYRAMPAŞA		ISTANBUL		
10		BEŞİKTAŞ		ISTANBUL		
11		BEYKOZ		ISTANBUL		
12		BEYLİKDÜZÜ		ISTANBUL		
13		BEYOĞLU		ISTANBUL		
14		BÜYÜKÇEKMECE		ISTANBUL		
15		ÇATALCA		ISTANBUL		
16		ÇEKMEKÖY		ISTANBUL		
17		ESENLER		ISTANBUL		
18		ESENYURT		ISTANBUL		
19		EYÜPSULTAN		ISTANBUL		
20		FATİH		ISTANBUL		
21		GAZİOSMANPAŞA		ISTANBUL		
22		GÜNGÖREN		ISTANBUL		
23		KADIKÖY		ISTANBUL		
24		KAĞITHANE		ISTANBUL		
25		KARTAL		ISTANBUL		
26		KÜÇÜKÇEKMECE		ISTANBUL		
27		MALTEPE		ISTANBUL		
28		PENDİK		ISTANBUL		
29		SANCAKTEPE		ISTANBUL		
30		SARIYER		ISTANBUL		
31		SİLİVRİ		ISTANBUL		
32		SULTANBEYLİ		ISTANBUL		
33		SULTANGAZİ		ISTANBUL		
34		ŞİLE		ISTANBUL		
35		ŞİŞLİ		ISTANBUL		
36		TUZLA		ISTANBUL		
37		ÜMRANİYE		ISTANBUL		
38		ÜSKÜDAR		ISTANBUL		
39		ZEYTİNBURNU		ISTANBUL		

Izmir:
1		ALİAĞA		İZMİR		
2		BALÇOVA		İZMİR		
3		BAYINDIR		İZMİR		
4		BAYRAKLI		İZMİR		
5		BERGAMA		İZMİR		
6		BEYDAĞ		İZMİR		
7		BORNOVA		İZMİR		
8		BUCA		İZMİR		
9		ÇEŞME		İZMİR		
10		ÇİĞLİ		İZMİR		
11		DİKİLİ		İZMİR		
12		FOÇA		İZMİR		
13		GAZİEMİR		İZMİR		
14		GÜZELBAHÇE		İZMİR		
15		KARABAĞLAR		İZMİR		
16		KARABURUN		İZMİR		
17		KARŞIYAKA		İZMİR		
18		KEMALPAŞA		İZMİR		
19		KINIK		İZMİR		
20		KİRAZ		İZMİR		
21		KONAK		İZMİR		
22		MENDERES		İZMİR		
23		MENEMEN		İZMİR		
24		NARLIDERE		İZMİR		
25		ÖDEMİŞ		İZMİR		
26		SEFERİHİSAR		İZMİR		
27		SELÇUK		İZMİR		
28		TİRE		İZMİR		
29		TORBALI		İZMİR		
30		URLA		İZMİR		

Kahramanmaraş:
1		AFŞİN		KAHRAMANMARAŞ		
2		ANDIRIN		KAHRAMANMARAŞ		
3		ÇAĞLAYANCERİT		KAHRAMANMARAŞ		
4		DULKADİROĞLU		KAHRAMANMARAŞ		
5		EKİNÖZÜ		KAHRAMANMARAŞ		
6		ELBİSTAN		KAHRAMANMARAŞ		
7		GÖKSUN		KAHRAMANMARAŞ		
8		NURHAK		KAHRAMANMARAŞ		
9		ONİKİŞUBAT		KAHRAMANMARAŞ		
10		PAZARCIK		KAHRAMANMARAŞ		
11		TÜRKOĞLU		KAHRAMANMARAŞ	

Karabük:
1		EFLANİ		KARABÜK		
2		ESKİPAZAR		KARABÜK		
3		OVACIK		KARABÜK		
4		SAFRANBOLU		KARABÜK		
5		YENİCE		KARABÜK		

Karaman:
1		AYRANCI		KARAMAN		
2		BAŞYAYLA		KARAMAN		
3		ERMENEK		KARAMAN		
4		KAZIMKARABEKİR		KARAMAN		
5		SARIVELİLER		KARAMAN		

Kars:
1		AKYAKA		KARS		
2		ARPAÇAY		KARS		
3		DİGOR		KARS		
4		KAĞIZMAN		KARS		
5		SARIKAMIŞ		KARS		
6		SELİM		KARS		
7		SUSUZ		KARS		

Kastamonu:
1		ABANA		KASTAMONU		
2		AĞLI		KASTAMONU		
3		ARAÇ		KASTAMONU		
4		AZDAVAY		KASTAMONU		
5		BOZKURT		KASTAMONU		
6		CİDE		KASTAMONU		
7		ÇATALZEYTİN		KASTAMONU		
8		DADAY		KASTAMONU		
9		DEVREKANİ		KASTAMONU		
10		DOĞANYURT		KASTAMONU		
11		HANÖNÜ		KASTAMONU		
12		İHSANGAZİ		KASTAMONU		
13		İNEBOLU		KASTAMONU		
14		KÜRE		KASTAMONU		
15		PINARBAŞI		KASTAMONU		
16		SEYDİLER		KASTAMONU		
17		ŞENPAZAR		KASTAMONU		
18		TAŞKÖPRÜ		KASTAMONU		
19		TOSYA		KASTAMONU		

Kayseri:
1		AKKIŞLA		KAYSERİ		
2		BÜNYAN		KAYSERİ		
3		DEVELİ		KAYSERİ		
4		FELAHİYE		KAYSERİ		
5		HACILAR		KAYSERİ		
6		İNCESU		KAYSERİ		
7		KOCASİNAN		KAYSERİ		
8		MELİKGAZİ		KAYSERİ		
9		ÖZVATAN		KAYSERİ		
10		PINARBAŞI		KAYSERİ		
11		SARIOĞLAN		KAYSERİ		
12		SARIZ		KAYSERİ		
13		TALAS		KAYSERİ		
14		TOMARZA		KAYSERİ		
15		YAHYALI		KAYSERİ		
16		YEŞİLHİSAR		KAYSERİ		

Kırıkkale:
1		BAHŞILI		KIRIKKALE		
2		BALIŞEYH		KIRIKKALE		
3		ÇELEBİ		KIRIKKALE		
4		DELİCE		KIRIKKALE		
5		KARAKEÇİLİ		KIRIKKALE		
6		KESKİN		KIRIKKALE		
7		SULAKYURT		KIRIKKALE		
8		YAHŞİHAN		KIRIKKALE		

Kırklareli:
1		BABAESKİ		KIRKLARELİ		
2		DEMİRKÖY		KIRKLARELİ		
3		KOFÇAZ		KIRKLARELİ		
4		LÜLEBURGAZ		KIRKLARELİ		
5		PEHLİVANKÖY		KIRKLARELİ		
6		PINARHİSAR		KIRKLARELİ		
7		VİZE		KIRKLARELİ		

Kırşehir:
1		AKÇAKENT		KIRŞEHİR		
2		AKPINAR		KIRŞEHİR		
3		BOZTEPE		KIRŞEHİR		
4		ÇİÇEKDAĞI		KIRŞEHİR		
5		KAMAN		KIRŞEHİR		
6		MUCUR		KIRŞEHİR		

Kilis:
1		ELBEYLİ		KİLİS		
2		MUSABEYLİ		KİLİS		
3		POLATELİ		KİLİS		

Kocaeli:
1		BAŞİSKELE		KOCAELİ		
2		ÇAYIROVA		KOCAELİ		
3		DARICA		KOCAELİ		
4		DERİNCE		KOCAELİ		
5		DİLOVASI		KOCAELİ		
6		GEBZE		KOCAELİ		
7		GÖLCÜK		KOCAELİ		
8		İZMİT		KOCAELİ		
9		KANDIRA		KOCAELİ		
10		KARAMÜRSEL		KOCAELİ		
11		KARTEPE		KOCAELİ		
12		KÖRFEZ		KOCAELİ		

Konya:
1		AHIRLI		KONYA		
2		AKÖREN		KONYA		
3		AKŞEHİR		KONYA		
4		ALTINEKİN		KONYA		
5		BEYŞEHİR		KONYA		
6		BOZKIR		KONYA		
7		CİHANBEYLİ		KONYA		
8		ÇELTİK		KONYA		
9		ÇUMRA		KONYA		
10		DERBENT		KONYA		
11		DEREBUCAK		KONYA		
12		DOĞANHİSAR		KONYA		
13		EMİRGAZİ		KONYA		
14		EREĞLİ		KONYA		
15		GÜNEYSINIR		KONYA		
16		HADİM		KONYA		
17		HALKAPINAR		KONYA		
18		HÜYÜK		KONYA		
19		ILGIN		KONYA		
20		KADINHANI		KONYA		
21		KARAPINAR		KONYA		
22		KARATAY		KONYA		
23		KULU		KONYA		
24		MERAM		KONYA		
25		SARAYÖNÜ		KONYA		
26		SELÇUKLU		KONYA		
27		SEYDİŞEHİR		KONYA		
28		TAŞKENT		KONYA		
29		TUZLUKÇU		KONYA		
30		YALIHÜYÜK		KONYA		
31		YUNAK		KONYA		

Kütahya:
1		ALTINTAŞ		KÜTAHYA		
2		ASLANAPA		KÜTAHYA		
3		ÇAVDARHİSAR		KÜTAHYA		
4		DOMANİÇ		KÜTAHYA		
5		DUMLUPINAR		KÜTAHYA		
6		EMET		KÜTAHYA		
7		GEDİZ		KÜTAHYA		
8		HİSARCIK		KÜTAHYA		
9		PAZARLAR		KÜTAHYA		
10		SİMAV		KÜTAHYA		
11		ŞAPHANE		KÜTAHYA		
12		TAVŞANLI		KÜTAHYA		

Malatya:
1		AKÇADAĞ		MALATYA		
2		ARAPGİR		MALATYA		
3		ARGUVAN		MALATYA		
4		BATTALGAZİ		MALATYA		
5		DARENDE		MALATYA		
6		DOĞANŞEHİR		MALATYA		
7		DOĞANYOL		MALATYA		
8		HEKİMHAN		MALATYA		
9		KALE		MALATYA		
10		KULUNCAK		MALATYA		
11		PÜTÜRGE		MALATYA		
12		YAZIHAN		MALATYA		
13		YEŞİLYURT		MALATYA		

Manisa:
1		AHMETLİ		MANİSA		
2		AKHİSAR		MANİSA		
3		ALAŞEHİR		MANİSA		
4		DEMİRCİ		MANİSA		
5		GÖLMARMARA		MANİSA		
6		GÖRDES		MANİSA		
7		KIRKAĞAÇ		MANİSA		
8		KÖPRÜBAŞI		MANİSA		
9		KULA		MANİSA		
10		SALİHLİ		MANİSA		
11		SARIGÖL		MANİSA		
12		SARUHANLI		MANİSA		
13		SELENDİ		MANİSA		
14		SOMA		MANİSA		
15		ŞEHZADELER		MANİSA		
16		TURGUTLU		MANİSA		
17		YUNUSEMRE		MANİSA		

Mardin:
1		ARTUKLU		MARDİN		
2		DARGEÇİT		MARDİN		
3		DERİK		MARDİN		
4		KIZILTEPE		MARDİN		
5		MAZIDAĞI		MARDİN		
6		MİDYAT		MARDİN		
7		NUSAYBİN		MARDİN		
8		ÖMERLİ		MARDİN		
9		SAVUR		MARDİN		
10		YEŞİLLİ		MARDİN		

Mersin:
1		AKDENİZ		MERSİN		
2		ANAMUR		MERSİN		
3		AYDINCIK		MERSİN		
4		BOZYAZI		MERSİN		
5		ÇAMLIYAYLA		MERSİN		
6		ERDEMLİ		MERSİN		
7		GÜLNAR		MERSİN		
8		MEZİTLİ		MERSİN		
9		MUT		MERSİN		
10		SİLİFKE		MERSİN		
11		TARSUS		MERSİN		
12		TOROSLAR		MERSİN		
13		YENİŞEHİR		MERSİN		

Muğla:
1		BODRUM		MUĞLA		
2		DALAMAN		MUĞLA		
3		DATÇA		MUĞLA		
4		FETHİYE		MUĞLA		
5		KAVAKLIDERE		MUĞLA		
6		KÖYCEĞİZ		MUĞLA		
7		MARMARİS		MUĞLA		
8		MENTEŞE		MUĞLA		
9		MİLAS		MUĞLA		
10		ORTACA		MUĞLA		
11		SEYDİKEMER		MUĞLA		
12		ULA		MUĞLA		
13		YATAĞAN		MUĞLA		

Muş:
1		BULANIK		MUŞ		
2		HASKÖY		MUŞ		
3		KORKUT		MUŞ		
4		MALAZGİRT		MUŞ		
5		VARTO		MUŞ		

Nevşehir:
1		ACIGÖL		NEVŞEHİR		
2		AVANOS		NEVŞEHİR		
3		DERİNKUYU		NEVŞEHİR		
4		GÜLŞEHİR		NEVŞEHİR		
5		HACIBEKTAŞ		NEVŞEHİR		
6		KOZAKLI		NEVŞEHİR		
7		ÜRGÜP		NEVŞEHİR		

Niğde:
1		ALTUNHİSAR		NİĞDE		
2		BOR		NİĞDE		
3		ÇAMARDI		NİĞDE		
4		ÇİFTLİK		NİĞDE		
5		ULUKIŞLA		NİĞDE		

Ordu:
1		AKKUŞ		ORDU		
2		ALTINORDU		ORDU		
3		AYBASTI		ORDU		
4		ÇAMAŞ		ORDU		
5		ÇATALPINAR		ORDU		
6		ÇAYBAŞI		ORDU		
7		FATSA		ORDU		
8		GÖLKÖY		ORDU		
9		GÜLYALI		ORDU		
10		GÜRGENTEPE		ORDU		
11		İKİZCE		ORDU		
12		KABADÜZ		ORDU		
13		KABATAŞ		ORDU		
14		KORGAN		ORDU		
15		KUMRU		ORDU		
16		MESUDİYE		ORDU		
17		PERŞEMBE		ORDU		
18		ULUBEY		ORDU		
19		ÜNYE		ORDU		

Osmaniye:
1		BAHÇE		OSMANİYE		
2		DÜZİÇİ		OSMANİYE		
3		HASANBEYLİ		OSMANİYE		
4		KADİRLİ		OSMANİYE		
5		SUMBAS		OSMANİYE		
6		TOPRAKKALE		OSMANİYE		

Rize:
1		ARDEŞEN		RİZE		
2		ÇAMLIHEMŞİN		RİZE		
3		ÇAYELİ		RİZE		
4		DEREPAZARI		RİZE		
5		FINDIKLI		RİZE		
6		GÜNEYSU		RİZE		
7		HEMŞİN		RİZE		
8		İKİZDERE		RİZE		
9		İYİDERE		RİZE		
10		KALKANDERE		RİZE		
11		PAZAR		RİZE		

Sakarya:
1		ADAPAZARI		SAKARYA		
2		AKYAZI		SAKARYA		
3		ARİFİYE		SAKARYA		
4		ERENLER		SAKARYA		
5		FERİZLİ		SAKARYA		
6		GEYVE		SAKARYA		
7		HENDEK		SAKARYA		
8		KARAPÜRÇEK		SAKARYA		
9		KARASU		SAKARYA		
10		KAYNARCA		SAKARYA		
11		KOCAALİ		SAKARYA		
12		PAMUKOVA		SAKARYA		
13		SAPANCA		SAKARYA		
14		SERDİVAN		SAKARYA		
15		SÖĞÜTLÜ		SAKARYA		
16		TARAKLI		SAKARYA		

Samsun:
1		19 MAYIS		SAMSUN		
2		ALAÇAM		SAMSUN		
3		ASARCIK		SAMSUN		
4		ATAKUM		SAMSUN		
5		AYVACIK		SAMSUN		
6		BAFRA		SAMSUN		
7		CANİK		SAMSUN		
8		ÇARŞAMBA		SAMSUN		
9		HAVZA		SAMSUN		
10		İLKADIM		SAMSUN		
11		KAVAK		SAMSUN		
12		LADİK		SAMSUN		
13		SALIPAZARI		SAMSUN		
14		TEKKEKÖY		SAMSUN		
15		TERME		SAMSUN		
16		VEZİRKÖPRÜ		SAMSUN		
17		YAKAKENT		SAMSUN		

Siirt:
1		BAYKAN		SİİRT		
2		ERUH		SİİRT		
3		KURTALAN		SİİRT		
4		PERVARİ		SİİRT		
5		ŞİRVAN		SİİRT		
6		TİLLO		SİİRT		

Sinop:
1		AYANCIK		SİNOP		
2		BOYABAT		SİNOP		
3		DİKMEN		SİNOP		
4		DURAĞAN		SİNOP		
5		ERFELEK		SİNOP		
6		GERZE		SİNOP		
7		SARAYDÜZÜ		SİNOP		
8		TÜRKELİ		SİNOP		

Sivas:
1		AKINCILAR		SİVAS		
2		ALTINYAYLA		SİVAS		
3		DİVRİĞİ		SİVAS		
4		DOĞANŞAR		SİVAS		
5		GEMEREK		SİVAS		
6		GÖLOVA		SİVAS		
7		GÜRÜN		SİVAS		
8		HAFİK		SİVAS		
9		İMRANLI		SİVAS		
10		KANGAL		SİVAS		
11		KOYULHİSAR		SİVAS		
12		SUŞEHRİ		SİVAS		
13		ŞARKIŞLA		SİVAS		
14		ULAŞ		SİVAS		
15		YILDIZELİ		SİVAS		
16		ZARA		SİVAS		

Şanlıurfa:
1		AKÇAKALE		ŞANLIURFA		
2		BİRECİK		ŞANLIURFA		
3		BOZOVA		ŞANLIURFA		
4		CEYLANPINAR		ŞANLIURFA		
5		EYYÜBİYE		ŞANLIURFA		
6		HALFETİ		ŞANLIURFA		
7		HALİLİYE		ŞANLIURFA		
8		HARRAN		ŞANLIURFA		
9		HİLVAN		ŞANLIURFA		
10		KARAKÖPRÜ		ŞANLIURFA		
11		SİVEREK		ŞANLIURFA		
12		SURUÇ		ŞANLIURFA		
13		VİRANŞEHİR		ŞANLIURFA		

Şırnak:
1		BEYTÜŞŞEBAP		ŞIRNAK		
2		CİZRE		ŞIRNAK		
3		GÜÇLÜKONAK		ŞIRNAK		
4		İDİL		ŞIRNAK		
5		SİLOPİ		ŞIRNAK		
6		ULUDERE		ŞIRNAK		

Tekirdağ:
1		ÇERKEZKÖY		TEKİRDAĞ		
2		ÇORLU		TEKİRDAĞ		
3		ERGENE		TEKİRDAĞ		
4		HAYRABOLU		TEKİRDAĞ		
5		KAPAKLI		TEKİRDAĞ		
6		MALKARA		TEKİRDAĞ		
7		MARMARAEREĞLİSİ		TEKİRDAĞ		
8		MURATLI		TEKİRDAĞ		
9		SARAY		TEKİRDAĞ		
10		SÜLEYMANPAŞA		TEKİRDAĞ		
11		ŞARKÖY		TEKİRDAĞ		

Tokat:
1		ALMUS		TOKAT		
2		ARTOVA		TOKAT		
3		BAŞÇİFTLİK		TOKAT		
4		ERBAA		TOKAT		
5		NİKSAR		TOKAT		
6		PAZAR		TOKAT		
7		REŞADİYE		TOKAT		
8		SULUSARAY		TOKAT		
9		TURHAL		TOKAT		
10		YEŞİLYURT		TOKAT		
11		ZİLE		TOKAT		

Trabzon:
1		AKÇAABAT		TRABZON		
2		ARAKLI		TRABZON		
3		ARSİN		TRABZON		
4		BEŞİKDÜZÜ		TRABZON		
5		ÇARŞIBAŞI		TRABZON		
6		ÇAYKARA		TRABZON		
7		DERNEKPAZARI		TRABZON		
8		DÜZKÖY		TRABZON		
9		HAYRAT		TRABZON		
10		KÖPRÜBAŞI		TRABZON		
11		MAÇKA		TRABZON		
12		OF		TRABZON		
13		ORTAHİSAR		TRABZON		
14		SÜRMENE		TRABZON		
15		ŞALPAZARI		TRABZON		
16		TONYA		TRABZON		
17		VAKFIKEBİR		TRABZON		
18		YOMRA		TRABZON		

Tunceli:
1		ÇEMİŞGEZEK		TUNCELİ		
2		HOZAT		TUNCELİ		
3		MAZGİRT		TUNCELİ		
4		NAZIMİYE		TUNCELİ		
5		OVACIK		TUNCELİ		
6		PERTEK		TUNCELİ		
7		PÜLÜMÜR		TUNCELİ		

Uşak:
1		BANAZ		UŞAK		
2		EŞME		UŞAK		
3		KARAHALLI		UŞAK		
4		SİVASLI		UŞAK		
5		ULUBEY		UŞAK		

Van:
1		BAHÇESARAY		VAN		
2		BAŞKALE		VAN		
3		ÇALDIRAN		VAN		
4		ÇATAK		VAN		
5		EDREMİT		VAN		
6		ERCİŞ		VAN		
7		GEVAŞ		VAN		
8		GÜRPINAR		VAN		
9		İPEKYOLU		VAN		
10		MURADİYE		VAN		
11		ÖZALP		VAN		
12		SARAY		VAN		
13		TUŞBA		VAN		

Yalova:
1		ALTINOVA		YALOVA		
2		ARMUTLU		YALOVA		
3		ÇINARCIK		YALOVA		
4		ÇİFTLİKKÖY		YALOVA		
5		TERMAL		YALOVA		

Yozgat:
1		AKDAĞMADENİ		YOZGAT		
2		AYDINCIK		YOZGAT		
3		BOĞAZLIYAN		YOZGAT		
4		ÇANDIR		YOZGAT		
5		ÇAYIRALAN		YOZGAT		
6		ÇEKEREK		YOZGAT		
7		KADIŞEHRİ		YOZGAT		
8		SARAYKENT		YOZGAT		
9		SARIKAYA		YOZGAT		
10		SORGUN		YOZGAT		
11		ŞEFAATLİ		YOZGAT		
12		YENİFAKILI		YOZGAT		
13		YERKÖY		YOZGAT		

Zonguldak:
1		ALAPLI		ZONGULDAK		
2		ÇAYCUMA		ZONGULDAK		
3		DEVREK		ZONGULDAK		
4		EREĞLİ		ZONGULDAK		
5		GÖKÇEBEY		ZONGULDAK		
6		KİLİMLİ		ZONGULDAK		
7		KOZLU		ZONGULDAK		





